const productos = [
    {
        id:1,
        nombre:"Escultura",
        desc:"Escultura",
        precio:1500,
        img:'src/img/escultura1.jpg',
        cantidad:1
    },
    {
        id:2,
        nombre:"Escultura",
        desc:"Escultura",
        precio:1500,
        img:'src/img/escultura2.jpg',
        cantidad:1
    },
    {
        id:3,
        nombre:"Escultura",
        desc:"Escultura",
        precio:2000,
        img:'src/img/escultura3.jpg',
        cantidad:1
    },
    {
        id:4,
        nombre:"Escultura",
        desc:"Escultura",
        precio:2000,
        img:'src/img/escultura4.jpg',
        cantidad:1
    },
    {
        id:5,
        nombre:"Textil",
        desc:"Textil",
        precio:3000,
        img:'src/img/textil1.jpg',
        cantidad:1
    },
    {
        id:6,
        nombre:"Textil",
        desc:"Textil",
        precio:4000,
        img:'src/img/textil2.jpg',
        cantidad:1
    },
    {
        id:7,
        nombre:"Textil",
        desc:"Textil",
        precio:4500,
        img:'src/img/textil3.jpg',
        cantidad:1
    },
    {
        id:8,
        nombre:"Textil",
        desc:"Textil",
        precio:4600,
        img:'src/img/textil4.jpg',
        cantidad:1
    },
    {
        id:9,
        nombre:"Textil",
        desc:"Textil",
        precio:5000,
        img:'src/img/textil5.jpg',
        cantidad:1
    },
    {
        id:10,
        nombre:"Textil",
        desc:"Textil",
        precio:6000,
        img:'src/img/textil6.jpg',
        cantidad:1
    }

]

export { productos };